### PR TITLE
Updates build.gradle

### PR DESCRIPTION
**Pull request by SticksPluto**
Makes it so only mcmod.info has the version required to update :D

### CODE REVIEW

**Comment by JustDesoroxxx** [comment]
1. You are still missing Jafama
2. We need to actually have the version number in the ModReference so you need to find a way to update it
3. Why did you even modify the Mod ID

**Comment by SticksPluto** [comment]
ModID must be all lowercase

**Comment by SticksPluto** [comment]
Answering 1. I'm not...
Answering 2. You're correct my bad set the version number in mcmod.info to the project ID

**Comment by JustDesoroxxx** [comment]
1. Embed does not work with FG5
2. Yeah but that won't fix it you need to find a way to replace the String in ModReference each time we compile

**Comment by SticksPluto** [comment]
I'll go do that and I saw embedded doesn't work I just left that there

**Pull request closed without merging**
